import 'package:advance_app/models/new.dart';
import 'package:flutter/material.dart';
import './models/players.dart';

List dataPlayers = [
  players(
    "p1",
    "Abdo Hamada",
    "GK",
    "assets/images/p1.jpg",
    5.5,
    true,
    Colors.red,
  ),
  players(
    "p2",
    "M.Farag",
    "GK",
    "assets/images/p2.jpg",
    6.5,
    false,
    Colors.green,
  ),
  players(
    "p3",
    "Gorge",
    "GK",
    "assets/images/p3.jpg",
    4.5,
    false,
    Colors.green,
  ),
  players(
    "p4",
    "Hossam Ali",
    "DF",
    "assets/images/p4.jpg",
    6.6,
    false,
    Colors.green,
  ),
  players(
    "p5",
    "AlSawy",
    "DF",
    "assets/images/p5.jpg",
    6.2,
    false,
    Colors.green,
  ),
  players(
    "p6",
    "Ziad Hossam",
    "DF",
    "assets/images/p6.jpg",
    6.7,
    false,
    Colors.green,
  ),
  players(
    "p7",
    "Seif zian",
    "DF",
    "assets/images/p7.jpg",
    6.7,
    false,
    Colors.green,
  ),
  players(
    "p8",
    "khaled",
    "MD",
    "assets/images/p8.jpg",
    10,
    false,
    Colors.green,
  ),
  players(
    "p9",
    "Fahmy",
    "MD",
    "assets/images/p9.jpg",
    10.5,
    false,
    Colors.green,
  ),
  players(
    "p10",
    "Mefrah",
    "MD",
    "assets/images/p10.jpg",
    8.5,
    false,
    Colors.green,
  ),
  players(
    "p11",
    "Mario",
    "MD",
    "assets/images/p11.jpg",
    8,
    false,
    Colors.green,
  ),
  players(
    "p12",
    "Kamal",
    "MD",
    "assets/images/p12.jpg",
    9.5,
    false,
    Colors.green,
  ),
  players(
    "p13",
    "Abanob Emad",
    "DF",
    "assets/images/p13.jpg",
    5.5,
    false,
    Colors.green,
  ),
  players(
    "p14",
    "Sayed",
    "MD",
    "assets/images/p14.jpg",
    6.5,
    false,
    Colors.green,
  ),
  players(
    "p15",
    "AbdelAkoy",
    "FW",
    "assets/images/p15.jpg",
    11,
    false,
    Colors.green,
  ),
  players(
    "p16",
    "Omar Ahmed",
    "FW",
    "assets/images/p16.jpg",
    7.5,
    false,
    Colors.yellow,
  ),
  players(
    "p17",
    "Farag",
    "FW",
    "assets/images/p17.jpg",
    12,
    false,
    Colors.green,
  ),
  players(
    "p18",
    "ALi",
    "MD",
    "assets/images/p18.jpg",
    5.5,
    true,
    Colors.red,
  ),
  players(
    "p19",
    "Hussen",
    "FW",
    "assets/images/p19.jpg",
    9.5,
    false,
    Colors.green,
  ),
  players(
    "p20",
    "Momen",
    "DF",
    "assets/images/p20.jpg",
    6.9,
    false,
    Colors.green,
  ),
  players(
    "p21",
    "Yousef",
    "DF",
    "assets/images/p21.jpg",
    5.7,
    false,
    Colors.green,
  ),
  // players(
  //   "p22",
  //   "Afra",
  //   "FW",
  //   "images/p0.jpg",
  //   11.5,
  //   false,
  //   Colors.green,
  // ),
];
const dataNews = [
  New("Khaled get highest rating", "assets/images/khaled.jpg", [
    Text(
      "khaled help his team to win where :",
      style: TextStyle(fontSize: 26, color: Colors.white),
      softWrap: true,
      overflow: TextOverflow.fade,
    ),
    Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Text(
        "khaled score 5 goals in the match",
        style: TextStyle(fontSize: 15, color: Colors.white),
      ),
    ),
    Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Text(
        "khaled give 10 assests in the match",
        style: TextStyle(fontSize: 15, color: Colors.white),
      ),
    ),
  ]),
  New("Hossam Score amazing Freekick", "assets/images/hossam.jpg", [
    Text(
      "Hossam help his team to win where :",
      style: TextStyle(fontSize: 26, color: Colors.white),
      softWrap: true,
      overflow: TextOverflow.fade,
    ),
    Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Text(
        "he score the goal ,be 15 apart",
        style: TextStyle(fontSize: 15, color: Colors.white),
      ),
    ),
    Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Text(
        "ziad hossam made this foul the goal",
        style: TextStyle(fontSize: 15, color: Colors.white),
      ),
    ),
  ]),
  New("abdo Hamada injured", "assets/images/hamada.jpg", [
    Text(
      "Dangerous injured in hand :",
      style: TextStyle(fontSize: 26, color: Colors.white),
      softWrap: true,
      overflow: TextOverflow.fade,
    ),
    Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Text(
        "abdo Hamada injured when mohamed Farag shoot a hared ball at him",
        style: TextStyle(fontSize: 15, color: Colors.white),
      ),
    ),
  ])
];
